# Generated by Django 3.2.25 on 2026-02-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='metadata',
            field=models.TextField(blank=True, help_text='JSON metadata for tool calls etc.', null=True),
        ),
        migrations.AddField(
            model_name='sessiondocument',
            name='collection_name',
            field=models.CharField(blank=True, db_index=True, help_text='ChromaDB collection name', max_length=255),
        ),
        migrations.AddField(
            model_name='sessiondocument',
            name='file_size',
            field=models.IntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='sessiondocument',
            name='file_type',
            field=models.CharField(blank=True, help_text='pdf, txt, docx, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='sessiondocument',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentpromptconfig',
            name='top_k',
            field=models.IntegerField(default=15, help_text='Number of relevant document chunks to retrieve'),
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool'), ('system', 'System')], max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='embedding_metadata',
            field=models.TextField(blank=True, help_text='JSON: chunk_count, status, metrics, etc.', null=True),
        ),
    ]
