# Generated by Django 4.2.7 on 2026-02-26 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chatbot', '0002_auto_20260224_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='started_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
